algoritmo "valor e salto 10 em 10 etc"
//
//
var
   valor, salto, contador: Inteiro

inicio
      contador <-0
      Escreva("Quer contar até quanto?")
      Leia(valor)
      Escreva(" Qual será o valor do salto?")
      Leia(salto)
      Enquanto (contador <=valor) faca
               Escreval (Contador)
               Contador <- contador + salto
      FimEnquanto
      Escreval ("Fim do Processo")


fimalgoritmo